### ISSUE TITLE
Please make a working sample Project

### ISSUE THREAD

**Issue by mustii82** [libgdx/gdx-pay#104]
The Example for this Library is very outdated and isn't working at all even when I do some Code Changes please make a working example to keep this Library alive and make it easier to port the iOS Backend later to the coming soon MultiOS Backend.

**Comment by keesvandieren** [comment]
Making a sample project is not that hard.

The gdx-pay contains subprojects gdx-pay-tests, gdx-pay-test-iosrobovm, gdx-pay-test-android. Those are in fact examples, but as they are part of the gdx-pay gradle project, it does not exactly reflect usage in other projects (e.g. Gradle dependency notation is different).

But they might be useful to make a sample project. Add them to a new libgdx project, replace (in the project names) 'test' with 'example' and we have something that should not be hard to make it work.

Currently I have no time to set this up, maybe someone from community is willing to help with this?

**Comment by MrCharli3** [comment]
+1, would really like a sample to look at, cannot get it to work on iOS.

**Comment by mustii82** [comment]
A Library without a working Sample is very bad... As All we know LibGDX had some hard times with the canceling of RoboVM. So a working sample with the actually MobiDevelop Build is very important for the future of Libgdx

**Comment by keesvandieren** [comment]
First step is to have Robovm open source edition officially supported.

Issue #123 is open, because The Robopods have not been released for long time. We cannot release a new gdx-pay version with snapshot dependencies.

Robopods have been released recently (4 days ago) so now #123 can be picked up. I am very busy right now, might be better in a month or so. We are happy to accept pull-requests.

Gdx-pay itself contains an example: gdx-pay-tests, gdx-pay-tests-iosrobovm contains example code of how to use gdx-pay on ios (samples for iOS MOE and android are also available in the -tests subprojects).

Also some people created issue reproduction projects, that might also help:
https://github.com/Berobasket/gdx-pay-issue
https://github.com/jsvitek/gdx_pay_issue118

If someone is willing to create a clean sample project with the new information, we are willing to reference it in the README.md and wiki pages.

**Comment by klaszlo8207** [comment]
+1 for this, the example project not worked at all

**Comment by keesvandieren** [comment]
Feel free to give it a start :-).

I have no time to create it, though if anyone would like to spent some time in create it, I am happy to provide feedback.

**Comment by mustii82** [comment]
it was be great if some can do the start who accomplish this library to work on a current project

**Comment by MrStahlfelge** [comment]
I will do that.

**Comment by MrStahlfelge** [comment]
Check out the example project here: https://github.com/MrStahlfelge/gdx-pay-example/
