### ISSUE TITLE
Consumables are restored on Android

### ISSUE THREAD

**Issue by alex-dorokhov** [libgdx/gdx-pay#201]
#### Issue details, reproduction steps/code
1. Buy a consumable item
2. Reinstall the app
3. Call PurchaseManager.restore
4. Consumable item is restored

Expected:
4. Only non-consumable items are restored.

Imagine the case: user has bought several packs of gold in the game. Then he spent everything and decide to start the game again, he removes the app data, but all of the gold is restored after reinstall.
As far as I remember that was not an issue in the previous google play implementation of gdx-pay. I believe it is also not a  case for RoboVM implementation.

#### Version of gdx-pay
0.12.1

#### Please select the affected platforms and payment service implementation
- [ ] Amazon
- [x] googlebilling
- [ ] googlepay
- [ ] apple iosmoe
- [ ] apple robovm

**Comment by MrStahlfelge** [comment]
You are right, the used method `queryPurchaseHistoryAsync` returns expired, consumed and cancelled purchases. That's not good.

The problem is what's better to do: 
* We can fix the problem with consumed products by skipping consumables. Problems: Cancelled entitlements will be restored, and Consumables that were not consumed by an application crash will be skipped. Unfortunately, there's no way to query if a returned purchase is cancelled or consumed.
* We can use `queryPurchases()` which only returns active purchases. Problem: The call is cached and may not restore everything, users may have to wipe their Google Play cache manually.

I think we should go with the second option to be safe. @keesvandieren what do you think?

**Comment by MrStahlfelge** [comment]
I changed the implementation to `queryPurchases()` because it is the recommended way to do. There's no way to know on the client if the returned purchases of `queryPurchaseHistoryAsync` are valid, this is only doable by server side verification. It is Google's secret why there is no way to retrieve the purchases by the user without using the cache.

@alex-dorokhov Thank you very much for pointing this out. I published 1.0.0-SNAPSHOT with the change. I tested the changed behaviour with cancelled Entitlements. Please test it with Consumables and come back here, then I will release 1.0.0 to fix this.

**Comment by alex-dorokhov** [comment]
I've tested with consumables:
- they are not restored anymore after consumption
- buying of consumables works as before
- if there is an exception during handlePurchase call, then consumable is restored after purchaseRestore is called

So everything work as expected.

Thank you for the quick fix!

**Comment by MrStahlfelge** [comment]
Thanks for coming back, 1.0.0 is released.
