### ISSUE TITLE
Google play billing upgrade ?

### ISSUE THREAD

**Issue by AlexandreHerbreteau** [libgdx/gdx-pay#246]
Hi !

I can see that the current embedded version of google play billing is the version 3, according to graddle:
compile 'com.android.billingclient:billing:3.0.1'

Do you plan to migrate to newest versions ?

Thanks !

**Comment by AlexandreHerbreteau** [comment]
Hello, thanks !

But I mean, there is no need to update gdx pay regarding to new features
that came with Google play billing 4 and now 5 ?

These new versions may require adaptations of gdx pay library, no ?

Le jeu. 26 mai 2022 à 14:35, Benjamin Schulte ***@***.***> a
écrit :

**Comment by MrStahlfelge** [comment]
If you need the newer versions, please check and make a PR for the necessary changes.

**Comment by leni8ec** [comment]
Starting on August 2, 2022, all new apps must use Billing Library version 4 or newer. By November 1, 2022, all updates to existing apps must use Billing Library version 4 or newer. [Learn more](https://developer.android.com/google/play/billing/deprecation-faq).

**Comment by keesvandieren** [comment]
@leni8ec / @AlexandreHerbreteau feel free to submit a PR with the upgrade

**Comment by leni8ec** [comment]
> @leni8ec / @AlexandreHerbreteau feel free to submit a PR with the upgrade

Thanks for your sarcasm. 

I just indicated the information for users of this package, since such a notification in the console can easily be overlooked.

**Comment by MrStahlfelge** [comment]
I doubt that it was sarcasm.

**Comment by keesvandieren** [comment]
There is no sarcastic intent in my message. I only try to make it clear that if someone makes the necessary changes, I am willy to invest some of my free time to review, test, merge and release the changes.

**Comment by AlexandreHerbreteau** [comment]
Hi.
Personally I have no technical capabilities to make such changes.


Le lun. 25 juil. 2022 à 13:36, Kees van Dieren ***@***.***> a
écrit :

**Comment by bitdream** [comment]
> I doubt that it was sarcasm.

Google has just given the deadlines for the Billing Library version 3. 
Could you help this upgrade?

**Comment by Trurl101** [comment]
So if no one is able to make this necessary changes: That means that gdx-pay is practically dead now?

A hint for potential new users that the project is abandoned would be sensible.

**Comment by MrStahlfelge** [comment]
It is not abandoned as long as people maintain and use it. We made it clear that we will review PRs and release new versions. However, it seems both maintainers do not use Google Play Billing themselves at the moment. Implementing something into the blue does not make much sense, it should be done by someone actually using the feature.

**Comment by Trurl101** [comment]
> It is not abandoned as long as people maintain and use it. We made it clear that we will review PRs and release new versions. However, it seems both maintainers do not use Google Play Billing themselves at the moment. Implementing something into the blue does not make much sense, it should be done by someone actually using the feature.

I understand that, and appreciate the work the maintainers put into gdx-pay. But I assume most people use libgdx and gdx-pay for Apple/Android apps?

Starting with November people will not be able to update their apps for Google Play if they use gdx-pay so any sensible developer that releases android apps and use gdx-pay will start looking for alternatives now instead of waiting if gdx-pay get updated.

I think only fraction of the users of gdx-pay would be able or know how to make PRs or make the necessary changes (at least I have not the slightest clue). "Someone" should make a PR will probably result in "no one" will do it.

That is no critic, I am always astonished and thankful that people invest so much work into such free projects and I fully understand when they can not invest time anymore (I surely have no time but I try to support the free projects I use with some money) but it doesn't change the fact that gdx-pay would be useless for some (probably many?) users without a google-play-billing-library update.

**Comment by obigu** [comment]
I'm not a gdx-pay user, I integrate billing libraries directly but upgrading from v3 to v4 (no need to add new features, just make it compile) is very straightfoward. Anybody that is able to develop a libGDX game is perfectly able to make the necessary changes on their own and, if they value this open-source project, to submit a PR and contribute. For anybody who has never contributed and needs this I'd encourage them to do it, it's a perfect chance to both solve their problem and learn a new skill.

**Comment by Mprompt** [comment]
Hello all,

Normally I never post but I see more people are in trouble with the push to billing v4 by Google. I took the current PurchaseManagerGoogleBilling.java file and updated it to work with the new billing v5 library. I'm not an expert on GitHub so I just attached the new .java file as an attachment to this post.

I tested it on our app and reoccurring purchases and one time purchases work, as well as restoring purchases. I did not test it thoroughly so be careful! I did not test subscriptions at all because our game does not use this.

[PurchaseManagerGoogleBilling.txt](https://github.com/libgdx/gdx-pay/files/9479607/PurchaseManagerGoogleBilling.txt)

**Comment by bitdream** [comment]
> Hello all,
> 
> Normally I never post but I see more people are in trouble with the push to billing v4 by Google. I took the current PurchaseManagerGoogleBilling.java file and updated it to work with the new billing v5 library. I'm not an expert on GitHub so I just attached the new .java file as an attachment to this post.
> 
> I tested it on our app and reoccurring purchases and one time purchases work, as well as restoring purchases. I did not test it thoroughly so be careful! I did not test subscriptions at all because our game does not use this.
> 
> [PurchaseManagerGoogleBilling.txt](https://github.com/libgdx/gdx-pay/files/9479607/PurchaseManagerGoogleBilling.txt)

Thank you but sorry why don't you make a pull request as these guys suggested?

**Comment by kharindev** [comment]
the pull request is ready, maybe it's time to merge it

**Comment by MrStahlfelge** [comment]
First it is time to review which I will do soon - anyone else can also review the changes, test it and make comments.

**Comment by shpowley** [comment]
> Hello all,
> 
> Normally I never post but I see more people are in trouble with the push to billing v4 by Google. I took the current PurchaseManagerGoogleBilling.java file and updated it to work with the new billing v5 library. I'm not an expert on GitHub so I just attached the new .java file as an attachment to this post.
> 
> I tested it on our app and reoccurring purchases and one time purchases work, as well as restoring purchases. I did not test it thoroughly so be careful! I did not test subscriptions at all because our game does not use this.
> 
> [PurchaseManagerGoogleBilling.txt](https://github.com/libgdx/gdx-pay/files/9479607/PurchaseManagerGoogleBilling.txt)

Thanks for posting this. It really helped.

**Comment by keesvandieren** [comment]
Resolved with #249
