### ISSUE TITLE
OUYA Backend: Order ID/Purchase Date

### ISSUE THREAD

**Issue by noblemaster** [libgdx/gdx-pay#27]
What would it take to supply order ID and Purchase date for each transaction for the OUYA backend? It's difficult to differentiate orders on a server if those are missing. At least Order ID would be very nice to have.

Also, I updated OpenIAB & the iOS backend to allow purchases for product identifiers that were added after both backends are installed. What would it take to add that to OUYA as well? 

No rush :-D

**Comment by just4phil** [comment]
hi chris!
i will take a look and check it out....
c u

**Comment by just4phil** [comment]
@noblemaster 
hi chris..... i tried to implement the stuff for OUYA backend but it seems to be dificult:

unique purchase id:
there is a unique purchase id in the json object that i can get for an actual purchase
but i have no idea how (if) i can get that for the receipts (receipts from ouya are older purchases)

purchaseDate:
here it is the other way around: for receipts i can get the date..... but a product doesnt contain a date.... so maybe new Date() could be ok, because the icoming product is the receipt in this moment

what shall we do?

bye
phil

**Comment by noblemaster** [comment]
That seems pretty oddly designed for OUYA!? Can't you pull always both the product & receipt when a purchase is made and use both together to generate a Transaction.java object?

**Comment by MrStahlfelge** [comment]
Closing this because Ouya is no more. If you think this issue is still relevant, feel free to reopen it.
